name: Backend CI Pipeline for Main Branches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vishnu@123
          POSTGRES_DB: codenest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Maven wrapper
      run: mvn -N io.takari:maven:wrapper

    - name: Install dependencies
      run: ./mvnw install
      working-directory: ./backend

    - name: Run tests
      run: ./mvnw test
      working-directory: ./backend

    - name: Build backend
      run: ./mvnw package
      working-directory: ./backend
