name: CICD Pipeline for main Branches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Run tests
        run: npm run test:ci
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vishnu@123
          POSTGRES_DB: codenest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install dependencies
        run: ./mvnw install
        working-directory: ./backend

      - name: Run tests
        run: ./mvnw test
        working-directory: ./backend

      - name: Build backend
        run: ./mvnw package
        working-directory: ./backend
